import { CheckCircle2, Download, FileJson, FileText, ShieldCheck, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { StatusBadge } from '@/components/common/badges';
import { SectionCard } from '@/components/common/cards';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/skeleton';
import { errorMessage } from '@/lib/api/errors';
import { formatIst } from '@/lib/datetime';
import { useCaseInfo, useGenerateJson, useGeneratePdf, useVerifyHash } from './api';

const label = 'text-xs uppercase tracking-wide text-muted-foreground';

function save(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function Alert({ children }: { children: string }) {
  return (
    <p role="alert" className="rounded-md border border-risk-critical/40 bg-risk-critical-soft px-3 py-2 text-sm text-risk-critical">
      {children}
    </p>
  );
}

function Hash({ sha256 }: { sha256: string }) {
  const { t } = useTranslation();
  const verify = useVerifyHash();
  const r = verify.data;
  return (
    <div className="space-y-2">
      <div className={label}>{t('SHA-256 (from the server)')}</div>
      <code data-testid="sha256" className="block break-all rounded-md border bg-muted px-2 py-1.5 font-mono text-xs">
        {sha256}
      </code>
      <div className="flex flex-wrap items-center gap-2">
        <Button type="button" variant="outline" size="sm" onClick={() => verify.mutate(sha256)} disabled={verify.isPending}>
          {verify.isPending ? <Spinner label="Verifying" /> : <ShieldCheck className="size-4" aria-hidden="true" />} Verify
        </Button>
        <div aria-live="polite" className="text-sm">
          {r?.match === true && (
            <StatusBadge tone="success" icon={<CheckCircle2 className="size-3.5" aria-hidden="true" />}>
              Verified: stored evidence matches this hash
            </StatusBadge>
          )}
          {r?.match === false && (
            <StatusBadge tone="danger" icon={<XCircle className="size-3.5" aria-hidden="true" />}>
              Mismatch: stored evidence does not match this hash
            </StatusBadge>
          )}
        </div>
      </div>
      {r?.report && (
        <p className="text-xs text-muted-foreground">
          Report {r.report.id} · {r.report.version} · recorded {formatIst(r.report.createdAt)}
        </p>
      )}
      {verify.isError && <Alert>{`Verification failed: ${errorMessage(verify.error)}`}</Alert>}
    </div>
  );
}

/**
 * Evidence report for one case. The server collects, hashes and renders everything; this only requests it, previews the
 * returned PDF bytes, and offers those same bytes (or the exact JSON text) for download. Each request records a new report on the server.
 */
export function ReportBuilder({ caseId, canGenerate }: { caseId: string; canGenerate: boolean }) {
  const { t } = useTranslation();
  const info = useCaseInfo(caseId);
  const pdf = useGeneratePdf(caseId);
  const json = useGenerateJson(caseId);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  const blob = pdf.data?.blob;
  useEffect(() => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    setPreviewUrl(url);
    return () => {
      URL.revokeObjectURL(url);
      setPreviewUrl(null);
    };
  }, [blob]);

  const c = info.data;
  return (
    <SectionCard title="Evidence report" description="Generated by the server from this case's own data. Each request is recorded as a new report." bodyClassName="space-y-5">
      <dl className="grid gap-3 sm:grid-cols-2">
        <div>
          <dt className={label}>{t('FIR number')}</dt>
          <dd className="text-sm">{info.isPending ? 'Loading…' : (c?.firNumber ?? 'Not recorded for this case')}</dd>
        </div>
        <div>
          <dt className={label}>{t('NCRP acknowledgement')}</dt>
          <dd className="text-sm">{info.isPending ? 'Loading…' : c && c.complaints.length ? c.complaints.map((x) => x.ackNo).join(', ') : 'No complaint linked'}</dd>
        </div>
      </dl>
      <p className="text-xs text-muted-foreground">
        FIR and acknowledgement are read from the case and cannot be edited here. The backend has no fields for IO name, rank or police station, so those are not part of the report and are not offered.
      </p>

      <div className="flex flex-wrap gap-2">
        <Button type="button" onClick={() => pdf.mutate()} disabled={!canGenerate || pdf.isPending}>
          {pdf.isPending ? <Spinner label="Generating PDF" /> : <FileText className="size-4" aria-hidden="true" />} {t('Generate PDF')}
        </Button>
        <Button type="button" variant="outline" onClick={() => json.mutate()} disabled={!canGenerate || json.isPending}>
          {json.isPending ? <Spinner label="Generating JSON" /> : <FileJson className="size-4" aria-hidden="true" />} {t('Generate JSON')}
        </Button>
      </div>
      {!canGenerate && <p className="text-xs text-muted-foreground">{t('Your role cannot generate reports.')}</p>}

      {pdf.isError && <Alert>{`PDF generation failed: ${errorMessage(pdf.error)}`}</Alert>}
      {pdf.data && (
        <div className="space-y-3 border-t pt-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-sm font-semibold">{t('PDF report')}</h3>
            <span className="text-xs text-muted-foreground">Generated in {pdf.data.ms} ms</span>
          </div>
          {previewUrl && <iframe title="PDF report preview" src={previewUrl} className="h-[32rem] w-full rounded-md border bg-muted" />}
          <Button type="button" variant="outline" size="sm" onClick={() => save(pdf.data.blob, `evidence-${pdf.data.reportId ?? caseId}.pdf`)}>
            <Download className="size-4" aria-hidden="true" /> {t('Download PDF')}
          </Button>
          {pdf.data.sha256 ? <Hash sha256={pdf.data.sha256} /> : <p className="text-xs text-muted-foreground">The server did not return a SHA-256 for this PDF.</p>}
        </div>
      )}

      {json.isError && <Alert>{`JSON generation failed: ${errorMessage(json.error)}`}</Alert>}
      {json.data && (
        <div className="space-y-3 border-t pt-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-sm font-semibold">JSON evidence ({json.data.report.version})</h3>
            <span className="text-xs text-muted-foreground">Generated in {json.data.ms} ms</span>
          </div>
          <ul className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">
            <li>{json.data.evidence.hops?.length ?? 0} hops</li>
            <li>{json.data.evidence.attribution?.length ?? 0} attributions</li>
            <li>{json.data.evidence.risk?.length ?? 0} risk entries</li>
            <li>{json.data.evidence.sources?.length ?? 0} data sources</li>
          </ul>
          {json.data.evidence.limitations && json.data.evidence.limitations.length > 0 && (
            <div>
              <div className={label}>Limitations stated by the report</div>
              <ul className="mt-1 list-disc space-y-0.5 pl-5 text-xs">
                {json.data.evidence.limitations.map((l) => (
                  <li key={l}>{l}</li>
                ))}
              </ul>
            </div>
          )}
          <Button type="button" variant="outline" size="sm" onClick={() => save(new Blob([json.data.text], { type: 'application/json' }), `evidence-${json.data.report.id}.json`)}>
            <Download className="size-4" aria-hidden="true" /> {t('Download JSON')}
          </Button>
          <Hash sha256={json.data.report.sha256} />
        </div>
      )}
    </SectionCard>
  );
}
